name: WorldEditor
main: WorldEditor\WorldEditor
version: 1.0.3
api: 1.2.0
author: Kagehis4
website: https://github.com/ryuzaki01/pocketmine-WorldEditor
commands:
 toggleeditwand:
  description: Переключиться в режим wand mode.
  usage: "/toggleeditwand"
  permission: worldeditor
 /cut:
  description: Вырезать выделенную область
  usage: "//cut"
  permission: worldeditor.command
 /copy:
  description: Копировать выделенную область
  usage: "//copy"
  permission: worldeditor.command
 /paste:
  description: Вставить выбранную область
  usage: "//paste"
  permission: worldeditor.command
 /sphere:
  description: Создать сферу.
  usage: "//sphere <блок> <радиус>"
  permission: worldeditor.command
 /hsphere:
  description: Создать пустую сферу.
  usage: "//hsphere <блок> <radius>"
  permission: worldeditor.command
 /desel:
  description: Deselects the current selection.
  usage: "//desel"
  permission: worldeditor.command
 /limit:
  description: Set your maximum number of blocks to change at most for all operations.
  usage: "//limit <limit>"
  permission: worldeditor.command
 /pos1:
  description: Set selection position #1 to the block above the one that you are standing on.
  usage: "//pos1"
  permission: worldeditor.command
 /pos2:
  description: Set selection position #2 to the block above the one that you are standing on.
  usage: "//pos2"
  permission: worldeditor.command
 /set:
  description: Set all blocks inside the selection region to a specified block(s)
  usage: "//set <blockID>"
  permission: worldeditor.command
 /replace:
  description: Replace all blocks of the specified block with another block(s) inside the region.
  usage: "//replace <fromBlock> <toBlock>"
  permission: worldeditor.command
 /help:
  description: Show list of commands
  usage: "//help"
  permission: worldeditor.command
 /wand:
  description: Gives you the "edit wand".
  usage: "//wand"
  permission: worldeditor.command
permissions:
    worldeditor:
        default: op
        description: "All the permissions to use the World Editor"
        children:
            worldeditor.command:
                default: op
                description: "Allow the usage of the WorldEditor command"
