name: WorldEditor
main: WorldEditor\WorldEditor
version: 1.0.3
api: 1.2.0
author: Kagehis4
website: https://github.com/ryuzaki01/pocketmine-WorldEditor
commands:
 toggleeditwand:
  description: Переключиться в режим wand mode.
  usage: "/toggleeditwand"
  permission: worldeditor
 /cut:
  description: Вырезать выделенную область
  usage: "//cut"
  permission: worldeditor.command
 /copy:
  description: Копировать выделенную область
  usage: "//copy"
  permission: worldeditor.command
 /paste:
  description: Вставить выбранную область
  usage: "//paste"
  permission: worldeditor.command
 /sphere:
  description: Создать сферу.
  usage: "//sphere <блок> <радиус>"
  permission: worldeditor.command
 /hsphere:
  description: Создать пустую сферу.
  usage: "//hsphere <блок> <радиус>"
  permission: worldeditor.command
 /desel:
  description: Отменить выделение
  usage: "//desel"
  permission: worldeditor.command
 /limit:
  description: Установить максимальное количество выделенных блоков для операторов
  usage: "//limit <limit>"
  permission: worldeditor.command
 /pos1:
  description: Установить первую точку
  usage: "//pos1"
  permission: worldeditor.command
 /pos2:
  description: Установить вторую точку
  usage: "//pos2"
  permission: worldeditor.command
 /set:
  description: Заполнить выделенный регион указанным блоком
  usage: "//set <ID блока>"
  permission: worldeditor.command
 /replace:
  description: Заменить выбранный блоки в регионе на указанные 
  usage: "//replace <Id блока> <ID блока>"
  permission: worldeditor.command
 /help:
  description: Посмотреть список всех команд
  usage: "//help"
  permission: worldeditor.command
 /wand:
  description: Получить инструмент для выделения региона
  usage: "//wand"
  permission: worldeditor.command
permissions:
    worldeditor:
        default: op
        description: "All the permissions to use the World Editor"
        children:
            worldeditor.command:
                default: op
                description: "Allow the usage of the WorldEditor command"
